version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true

volumes:
  node_modules:
